### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by hairpin666** [RonnyWeiss/Apex-Dynamic-Tooltip#1]
Hi,

I'd like to try your plugin, it shows the data but throws an error with the standard config (left it as is):

Error while try to parse targetConfig. Please check your Config JSON. Standard Config will be used.
dynamictooltip.pkgd.min.js:61:21
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Stack trace:
jsonSaveExtend@https://apex.oracle.com/pls/apex/heifi/r/130180/files/plugin/59375078603676025763/v1298/dynamictooltip.pkgd.min.js:59:36
initialize@https://apex.oracle.com/pls/apex/heifi/r/130180/files/plugin/59375078603676025763/v1298/dynamictooltip.pkgd.min.js:155:44
javascriptFunction@https://apex.oracle.com/pls/apex/f?p=130180:1:128347748875580::::::168:3
da.doAction@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:21:5162
da.doActions@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:21:3661
da.actions/<@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:21:2594
each@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:2571
each@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:1238
da.actions@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:21:2291
da.init/<@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:21:972
each@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:2571
each@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:1238
da.init@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:21:126
@https://apex.oracle.com/pls/apex/f?p=130180:1:128347748875580::::::209:13
@https://apex.oracle.com/pls/apex/f?p=130180:1:128347748875580::::::209:2
u@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:27452
add@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:27735
@https://apex.oracle.com/pls/apex/f?p=130180:1:128347748875580::::::204:1
a.init@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:14:5323
@https://apex.oracle.com/pls/apex/f?p=130180:1:128347748875580::::::202:1
l@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:29373
a/</c<@https://static.oracle.com/cdn/apex/19.1.0.00.15/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:29677
dynamictooltip.pkgd.min.js:62:21

**Comment by RonnyWeiss** [comment]
please check you json configuration there is an error in there. Do you use the default value?

**Comment by RonnyWeiss** [comment]
No answer since 2 weeks. So I will close. Reopen if needed
