### ISSUE TITLE
Allow Mouse Hover

### ISSUE THREAD

**Issue by Ora-solution** [RonnyWeiss/Apex-Dynamic-Tooltip#3]
Hi Ronny,

Thanks again for your another wonderful plugin to make Apex Application more productive and beautiful. 

This is not exactly an issue but need a workaround to mouse hover on this dynamic tooltip. 

I'm showing a link on this tooltip and I want allow user to mouse click on this link, please suggest me if is there any workaround to achieve this. 

Once again, I always appreciate your efforts in this regards.

Waqar Siddiqui

**Comment by RonnyWeiss** [comment]
Hello

Thank you for question! 


This is not possible because tooltips comes on mouseover an element. You want that the tooltip is not hidden on mouseout and that you can click on the link when tooltip is shown statically on page or ist that wrong?

Maybe a ropdown menu on our element is better then the tooltip isn't it? 

Kind regards

Ronny

**Comment by Ora-solution** [comment]
Hello,

Thank you for your response on this.

Yes, I think you are quite right, definitely drop-down menu would be the better option but I'm not expert in JS/CSS. Also, I was using this plugin in most of my pages and wanted to know if this could be possible, so I would be able to use this in both ways, something like this: 
![image](https://user-images.githubusercontent.com/4133566/85181165-af122400-b29e-11ea-8e82-fddf3b98ec92.png)


Thanks & regards,

Waqar Siddiqui

**Comment by RonnyWeiss** [comment]
Hello

Maybe a New plugin would be the solution 😉 Could be context Menu or such a popup Menü on click and maybe I have an idea for you I could implement Option to Show tooltip Not only on hover. Maybe I could implement that it comes on click and hides when click outside of tooltip Region. It's easy to implement and could help you?

Kind regards

Ronny

**Comment by Ora-solution** [comment]
Hi,

Whoa, yes, definitely, and even adding little delay to hide tooltip and if this gets cursor on itself then wait until cursor move out. 

Further, that will be great if you could implement this option on the same, and I hope this will serve others as well.

Thanks & regards,

Waqar Siddiqui

**Comment by Ora-solution** [comment]
Hello

On the weekend I did some googling and tried to make little changes in "dynamictooltip.pkgd.min.js" files, and after making little changes somehow I was able to get required result, but definitely there will be a proper way to get this done. I wanted to share with you the changes I made in the code.

change this:
``` javascript
show: function (e, t, o) {
    try {
        if (0 == $("#dynToolTip").length) {
            var n = $("<div></div>").attr("id", "dynToolTip").css("max-width", "400px").css("position", "absolute").css("top", "0px").css("left", "0px").css("z-index", "2000").css("background-color", "rgba(240, 240, 240, 1)").css("padding", "10px").css("display", "block").css("top", "0").css("overflow-wrap", "break-word").css("word-wrap", "break-word").css("-ms-hyphens", "auto").css("-moz-hyphens", "auto").css("-webkit-hyphens", "auto").css("hyphens", "auto");
            t && n.css("background-color", t),
            o && n.css("max-width", o),
            $("body").append(n)
        } else
            $("#dynToolTip").css("visibility", "visible");
        $("#dynToolTip").html(e),
        $("#dynToolTip").find("*").css("max-width", "100%").css("overflow-wrap", "break-word").css("word-wrap", "break-word").css("-ms-hyphens", "auto").css("-moz-hyphens", "auto").css("-webkit-hyphens", "auto").css("hyphens", "auto").css("white-space", "normal"),
        $("#dynToolTip").find("img").css("object-fit", "contain").css("object-position", "50% 0%")
    } catch (e) {
        console.error("Error while try to show tooltip"),
        console.error(e)
    }
},
setPosition: function (e) {
    $("#dynToolTip").position({
        my: "left+6 top+6",
        of: e,
        collision: "flipfit"
    })
},
hide: function () {
    $("#dynToolTip").css("visibility", "hidden")
},
```

to this:
``` javascript

show: function (e, t, o) {
    try {
        if (0 == $("#dynToolTip").length) {
            var n = $("<div></div>").attr("id", "dynToolTip").css("max-width", "400px").css("position", "absolute").css("top", "0px").css("left", "0px").css("z-index", "2000").css("background-color", "rgba(240, 240, 240, 1)").css("padding", "10px").css("display", "block").css("top", "0").css("overflow-wrap", "break-word").css("word-wrap", "break-word").css("-ms-hyphens", "auto").css("-moz-hyphens", "auto").css("-webkit-hyphens", "auto").css("hyphens", "auto");
            t && n.css("background-color", t),
            o && n.css("max-width", o),
            $("body").append(n)
        } else
            $("#dynToolTip").stop().css("visibility", "visible").css("opacity", "");
        $("#dynToolTip").html(e),
        $("#dynToolTip").find("*").css("max-width", "100%").css("overflow-wrap", "break-word").css("word-wrap", "break-word").css("-ms-hyphens", "auto").css("-moz-hyphens", "auto").css("-webkit-hyphens", "auto").css("hyphens", "auto").css("white-space", "normal"),
        $("#dynToolTip").find("img").css("object-fit", "contain").css("object-position", "50% 0%"),
        $("#dynToolTip").on("mouseenter", function (t) {
            $("#dynToolTip").stop().css("visibility", "visible").css("opacity", "");
        }),
        $("#dynToolTip").on("mouseleave", function (t) {
            $("#dynToolTip").animate({
                opacity: 0.0
            }, 200, function () {
                $("#dynToolTip").remove();
            });
        })
    } catch (e) {
        console.error("Error while try to show tooltip"),
        console.error(e)
    }
},
setPosition: function (e) {
    $("#dynToolTip").position({
        my: "left+6 top+6",
        of: e,
        collision: "flipfit"
    }).stop().css("visibility", "visible").css("opacity", "")
},
hide: function () {
    $("#dynToolTip").animate({
        opacity: 0.0
    }, 200, function () {
        $("#dynToolTip").css("visibility", "hidden").css("opacity", "");
    });
},
```

Regards,

Waqar Siddiqui

**Comment by RonnyWeiss** [comment]
Hello 

Thank you for the code but I used a little different implemention and published it some minutes ago. Now you can open the tt by click on target elements. The method (click, mouseover) can be now set in plug-in attributes. So maybe you can try new version and it would be nice if you have some feedback for me.

Kind regards

Ronny

**Comment by Ora-solution** [comment]
Hi,

Thanks to manage for this updated version, these changes really appreciable.

Regards,
Waqar Siddiqui
