### ISSUE TITLE
Error while try to parse targetConfig

### ISSUE THREAD

**Issue by pasiarz** [RonnyWeiss/Apex-Dynamic-Tooltip#4]
Hi,

I have a problem with your plugin. 

My JSON

{
  "backgroundColor": "#d7d7d7",
   "color": "white",
  "maxWidth": "400px",
  "ajaxDelay": 300
}

SQL Source
SELECT
    :P40_KEY AS TOOLTIP
FROM
    DUAL

Object { msg: "Error while try to parse targetConfig. Please check your Config JSON. Standard Config will be used.", err: SyntaxError, targetConfig: "" }
 
Object { name: "APEX-Dynamic-Tooltip", info: {…} }
desktop_all.min.js:7:1218
    error https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:7
    error https://appl-testebs.fideltronik.com.pl/apex/apex_ebs/r/112/files/plugin/42403870841405258805/v1321/dynamictooltip.pkgd.min.js:1
    jsonSaveExtend https://appl-testebs.fideltronik.com.pl/apex/apex_ebs/r/112/files/plugin/42403870841405258805/v1321/dynamictooltip.pkgd.min.js:1
    initialize https://appl-testebs.fideltronik.com.pl/apex/apex_ebs/r/112/files/plugin/42403870841405258805/v1321/dynamictooltip.pkgd.min.js:1
    javascriptFunction https://appl-testebs.fideltronik.com.pl/apex/f?p=112:40:12591059444435::NO::::2812
    doAction https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:23
    doActions https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:23
    actions https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:23
    each https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    each https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    actions https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:23
    init https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:23
    each https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    each https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    init https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:23
    <anonymous> https://appl-testebs.fideltronik.com.pl/apex/f?p=112:40:12591059444435::NO::::2875
    <anonymous> https://appl-testebs.fideltronik.com.pl/apex/f?p=112:40:12591059444435::NO::::2875
    i https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    add https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    <anonymous> https://appl-testebs.fideltronik.com.pl/apex/f?p=112:40:12591059444435::NO::::2860
    init https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:16
    <anonymous> https://appl-testebs.fideltronik.com.pl/apex/f?p=112:40:12591059444435::NO::::2858
    j https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    k https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    (Async: setTimeout handler)
    g https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    i https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    fireWith https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    fire https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    i https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    fireWith https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    ready https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    R https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:3
    (Async: EventListener.handleEvent)
    <anonymous> https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:3
    <anonymous> https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2
    <anonymous> https://appl-testebs.fideltronik.com.pl/i/libraries/apex/minified/desktop_all.min.js?v=18.2.0.00.12:2

**Comment by RonnyWeiss** [comment]
Hello

Thank you for your Issue! I can'T reproduce the problem. in my sample App. But i seem that you configJSON was not correctly save in -APEX. Could you please readd the plug-in again check that json in configJSON is valid?

**Comment by pasiarz** [comment]
Hi, thank you for involvement. I tried to add this again but still the same. Additionally I used in another case original (defaults) values of JSON and SQL and result is the same....

Seeded JSON
{
  "backgroundColor": "rgba(240, 240, 240, 1)",
  "maxWidth": "400px",
  "ajaxDelay": 300
}

Any suggestions? Of course although browser put the the errors then plugin working properly :)

**Comment by RonnyWeiss** [comment]
what APEX version are you using?

could you please check if the error also occurs in my sample app, when using there the plug-in?

**Comment by pasiarz** [comment]
Hi,
Product Build | 18.2.0.00.12
Nope your Simple app working fine.

**Comment by RonnyWeiss** [comment]
Can you please create a new app in your workscpae and add the plug-in there? I think it's maybe a problem with old jquery version that are set by an old app that is jsut upgraded to APEX 18.2?!

**Comment by RonnyWeiss** [comment]
Close because no reaction! Please reopen if problem still exists
