### ISSUE TITLE
syntax error JSON.parse

### ISSUE THREAD

**Issue by mwpulles** [RonnyWeiss/Apex-Dynamic-Tooltip#5]
Hi Ronny, I love your tooltip tool. For a new app I downloaded your package, installed it and got an error while hovering over the page

---
err: SyntaxError: JSON.parse: expected double-quoted property name at line 2 column 48 of the JSON data
​
module: "util.js"
​
msg: "Error while try to parse targetConfig. Please check your Config JSON. Standard Config will be used."
​
targetConfig: "{\n  \"backgroundColor\": \"rgba(240, 240, 240, 1)\", /* sets the background color of the tooltip */\n  \"maxWidth\": \"400px\", /* sets the max width of the tooltip */\n  \"ajaxDelay\": 300 /* sets the waiting time when hover with mouse before data is loading */\n}"
​
<prototype>: Object { … }
desktop_all.min.js:5:1107

---
I hope this is helpful enough for you. Please let me know if I can help.
Ciao, Mark

**Comment by RonnyWeiss** [comment]
Can you please check that your json is a valid json e.g. with https://jsonformatter.curiousconcept.com/

**Comment by mwpulles** [comment]
Hi Ronny,
Thanks for your reply!
There is no JSON involved other than applied with the default setup.  V1.7.1 of the plugin is used.

Here is what the current setup is about. I created a IG with a column "CAR" in it. 
-Setup for HTML expression: <span class="tt_car" pk="#PEOPLE_SID#">#CAR#</span>
-DA for on mouse enter, When fires on jQuery Sel.: .tt_car

-TRUE action: APEX Dyna Tooltip, element selector: .tt_car , PriKey: P1_PK
-SQLSource: select 'test' as tooltip, '' as backgroundcolor from dual;
-Option JSON: 
{
  "backgroundColor": "rgba(240, 240, 240, 1)", /* sets the background color of the tooltip */
  "maxWidth": "400px", /* sets the max width of the tooltip */
  "ajaxDelay": 300 /* sets the waiting time when hover with mouse before data is loading */
}
For a test I refreshed the page (clean (FF) console). Carefully moved the mousepointer towards a record and entered a CAR column => mouseover event occurs. The result of this (single) event is attached to this comment. 

[Tooltip_error.txt](https://github.com/RonnyWeiss/Apex-Dynamic-Tooltip/files/6114170/Tooltip_error.txt)

Again, I hope this is helpful enough for you. Please let me know if I can help.
Ciao, Mark

**Comment by RonnyWeiss** [comment]
Please check your json on e.g. with https://jsonformatter.curiousconcept.com/

Because when this is your json it's not valid because /**/ comments in json is not allowed ;-)

**Comment by mwpulles** [comment]
Hi Ronny,
Sorry :-( my bad. Corrected it immediately and tested again. Same conditions, still 1 error remains. 
Find this one attached. 
[Tooltip_error2.txt](https://github.com/RonnyWeiss/Apex-Dynamic-Tooltip/files/6114256/Tooltip_error2.txt)

Cheers,
Mark

**Comment by RonnyWeiss** [comment]
Please send me your json

**Comment by mwpulles** [comment]
hereby:
{
  "backgroundColor": "rgba(240, 240, 240, 1)",
  "maxWidth": "400px",
  "ajaxDelay": 300
}

**Comment by RonnyWeiss** [comment]
tried it and it worked! So please check if there are any other instances of this plugin on your page or try it on a new page with this json :-)

**Comment by mwpulles** [comment]
Can there be only one instance of this plugin per page? If so than this is probably the cause. I have 3 of these guys. 
But still all three tooltip info were displayed as expected to the user. 
I'll also try to setup a fresh app and page to check this out.  May I contact you for the outcome?

**Comment by RonnyWeiss** [comment]
Not that is not the Problem you can have n instances but please check all json configs 😉

**Comment by RonnyWeiss** [comment]
Does it work?

**Comment by mwpulles** [comment]
Hi Ronny,
Unfortunately not. Clean JSON
I was very busy with implementation of a new release, sorry.
Sincerely,
Mark Pulles



Op di 16 mrt. 2021 om 12:38 schreef Ronny Weiss ***@***.***>:

**Comment by whenothers** [comment]
Hi Ronny,

is there a solution? We're currently experiencing the same issue.

Thanks,
Andreas

**Comment by RonnyWeiss** [comment]
Hi Andreas

did you check your json if that is correct? 

Kind regards Ronny

**Comment by whenothers** [comment]
yes, checked.

{
   "backgroundColor":"rgba(240, 240, 240, 1)",
   "maxWidth":"400px",
   "ajaxDelay":300
}

**Comment by RonnyWeiss** [comment]
And what error do you get in console?

**Comment by whenothers** [comment]
Object { module: "util.js", msg: "Error while try to parse targetConfig. Please check your Config JSON. Standard Config will be used.", err: SyntaxError, targetConfig: "" }
​err: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
​module: "util.js"
​msg: "Error while try to parse targetConfig. Please check your Config JSON. Standard Config will be used."
​targetConfig: ""

**Comment by RonnyWeiss** [comment]
Could you please send me a sample app or access on a sample apex on apex.oracle.com where the error occurs?

**Comment by whenothers** [comment]
Thanks for the opportunity - this will probably take some days and I'm not sure if I can extract the client's page and still preserve the error :-)

Anyway, I'll try.
Thanks a lot and enjoy the virtual DOAG 2021.
